import 'package:vexa_show_do_bilionario/Areas/Home/Models/Config.dart';
import 'package:vexa_show_do_bilionario/Areas/Home/Models/Perguntas.dart';

List<int> moneyLevel = [0, 1, 3, 5, 10, 20, 30, 50, 100, 150, 250, 500, 1000];

List<Perguntas> litaPerguntas = [
  Perguntas("Em que ano foi lançado o primeiro álbum solo do Michael Jackson?", ["1971", "1979", "1986", "1972"], 0),
  Perguntas("Quem inventou o telefone celular?", ["Alexander Graham Bell", "James Russell", "Martin Cooper", "Steve Jobs"], 2),
  Perguntas("Quem foi o criador do filme 'Vingadores'?", ["Joss Whedon", "Stan Lee", "Martin Scorsese", "Christopher Nolan"], 0),
  Perguntas("Quantos elementos foram descobertos pela Indira Gandhi?", ["118", "30", "4", "126"], 3),
  Perguntas("Em que ano foi lançado o filme Matrix?", ["1999", "1998", "1992", "2001"], 0),
  Perguntas("Quem foi o primeiro presidente dos Estados Unidos?", ["George Washington", "Thomas Jefferson", "John Adams", "James Madison"], 0),
  Perguntas("Quem descobriu o Brasil?", ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães"], 1),
  Perguntas("Quem escreveu a obra 'Guerra e Paz'?", ["Charles Dickens", "Leo Tolstoy", "Fyodor Dostoevsky", "Honoré de Balzac"], 1),
  Perguntas("Qual a pessoa mais velha a ter servido como presidente dos Estados Unidos?", ["Dwight Eisenhower", "Ronald Reagan", "Gerald Ford", "Donald Trump"], 3),
  Perguntas("Qual foi o primeiro país a declarar a independência da Coroa Britânica?", ["França", "Canadá", "Colômbia", "EUA"], 3),
  Perguntas("Quem escreveu o famoso livro de contos de fadas, 'Os Irmãos Grimm'?", ["Charles Perrault", "Jacob Grimm", "Wilhelm Grimm", "Hans Christian Andersen"], 2),
  Perguntas("Quem escreveu a obra 'Hamlet'?", ["William Shakespeare", "John Milton", "Edgar Allan Poe", "Oscar Wilde"], 0),
  Perguntas("Segundo o mito grego, quem foi o criador de Pandora?", ["Aquiles", "Júpiter", "Hercules", "Prometeu"], 3),
  Perguntas("Quem desenvolveu a teoria da relatividade geral?", ["Albert Einstein", "Max Planck", "Isaac Newton", "Stephen Hawking"], 0),
  Perguntas("Quantos estados americanos existem?", ["24", "48", "50", "52"], 2),
  Perguntas("Quantos estados brasileiros existem?", ["30", "26", "25", "24"], 1),
  Perguntas("Que cidade abrigou as primeiras Olimpíadas modernas?", ["Sidney", "Londres", "Atenas", "Nova York"], 2),
  Perguntas("Na literatura, quem é a personagem do famoso livro de J. R. R. Tolkien 'O Senhor dos Anéis'?", ["Harry Potter", "Frodo Baggins", "Gandalf", "Oscar Wilde"], 1),
  Perguntas("Qual é a capital da Grécia? ", ["Roma", "Atenas", "Paris", "Londres"], 1),
  Perguntas("Quais animais marinhos são considerados os maiores mamíferos existentes? ", ["elefantes", "baleias", "golfinhos", "macacos"], 1),
  Perguntas("Qual destes países NÃO faz parte da União Europeia? ", ["Reino Unido", "Alemanha", "Suécia", "Rússia"], 3),
  Perguntas("Quantas gotas de água cabem em uma xícara de chá? ", ["10", "20", "50", "100"], 2),
  Perguntas("Que lugar é conhecido como Terra da Meia-Noite? ", ["Alasca", "Groenlândia", "Irlanda", "Finlândia"], 1),
  Perguntas("Qual destes instrumentos musicais é considerado de cordas? ", ["violino", "piano", "trompete", "clarinete"], 0),
  Perguntas("Quem foi o primeiro astronauta a pisar na Lua? ", ["Neil Armstrong", "Yoichi Hoshi", "Alexei Leonov", "John Glenn"], 0),
  Perguntas("Onde foi realizado o primeiro Campeonato Mundial de Futebol? ", ["Inglaterra", "Brasil", "Uruguai", "Itália"], 2),
  Perguntas("Quem pintou 'La Gioconda' ou 'Mona Lisa'? ", ["Leonardo da Vinci", "Michelangelo", "Rafael Sanzio", "Vincent Van Gogh"], 0),
  Perguntas("Que cor é o sol? ", ["Azul", "Vermelho", "Verde", "Amarelo"], 3),
  Perguntas("Quantas estrelas tem a bandeira brasileira? ", ["Cinco", "Sete", "Nove", "Onze"], 1),
  Perguntas("Que criatura mítica retratada com cabeça e corpo humano mas com asas de águia? ", ["Anjo", "Grifo", "Unicórnio", "Sátiro"], 0),
  Perguntas("Onde estão localizados os Grandes Lagos dos Estados Unidos da América? ", ["Nova York", "Michigan", "Minnesota", "Wisconsin"], 1),
  Perguntas("Quantos planetas existem no Sistema Solar? ", ["Seis", "Sete", "Oito", "Nove"], 2),
  Perguntas("A Ação de colocar vários objetos um em cima do outro chama-se ", ["Entralhar", "Interceder", "Empilhar", "Interceptar"], 2),
  Perguntas("Qual é o signo do zodíaco que finaliza e inicia todos os anos? ", ["Capricórnio", "Aquário", "Sargitário", "Peixer"], 0),
  Perguntas("Qual é o nome da tabela onde se apresentam os elementos químicos? ", ["Geográfia", "Matemática", "Periódica", "Estatística"], 2),
  Perguntas("Em um incêndio, qual lugar devemos dar preferência para fugir do fogo? ", ["Saída De Emergência", "Armário", "Corredor", "Elevador"], 0),
  Perguntas("Na linguagem popular tetéia é uma pessoa ", ["Manhosa", "Chorona", "Infeliz", "Graciosa"], 3),
  Perguntas("Qual é o feminino de frade? ", ["Pitonisa", "Freira", "Padre", "Sacerdotisa"], 1),
  Perguntas("Como ficou conhecido o período no qual o café era o principal produto brasileiro?", ["Ciclo do cacau", "Ciclo do carbono", "Ciclo da cafeína", "Ciclo da café"], 3),
  Perguntas("O termo 'cabra-macho' refere-se a um indivíduo:", ["Tímido", "Valente", "Fraco", "Medroso"], 1),
  Perguntas("A palavra 'muito' constitui um:", ["Verbo", "Adjetivo", "Substantivo", "Advébio"], 3),
  Perguntas("Qual bicho transmite Doença de Chagas?", ["Abelha", "Barata", "Pulga", "Barbeiro"], 3),
  Perguntas("Qual fruto é conhecido no Norte e Nordeste como 'jerimum'?", ["Cajú", "ChuChu", "Abóbora", "Côco"], 2),
  Perguntas("Qual é o coletivo de cães?", ["Matilha", "Rebanho", "Alcateia", "Manada"], 0),
  Perguntas("Qual é o triângulo que tem todos os lados diferentes?", ["Equilátero", "Isóceles", "Escaleno", "Trapézio"], 2),
  Perguntas("Quem compôs o Hino da Independência?", ["Dom Pedro I.", "Manuel Bandeira", "Castro Alves", "Carlos Gomes"], 0),
  Perguntas("Qual é o antônimo de 'malograr'?", ["Perder", "Fracassar", "Conseguir", "Desprezar"], 2),
  Perguntas("Em que país nasceu Carmem Miranda?", ["Brasil", "Espanha", "Portugal", "Argentina"], 2),
  Perguntas("Qual foi o último Presidente do período da ditadura militar no Brasil?", ["Luiz Inácio", "João Fiqueredo", "Costa e Silvia", "Jair Messias"], 1),
  Perguntas("Seguindo a sequência do baralho, qual carta vem depois do dez?", ["Rei", "Valente", "Nove", "As"], 1),
  Perguntas("O adjetivo 'venoso' está relacionado a:", ["Veia", "Vênia", "Vento", "Vala"], 0),
  Perguntas("Que nome se dá à purificação por meio da água?", ["Abolição", "Ablução", "Abnegação", "Abrupção"], 1),
  Perguntas("Qual montanha se localiza entre a fronteira do Tibet com o Nepal?", ["Monte Everest", "Monte Carlo", "Monte fugi", "Monte Branco"], 0),
  Perguntas("Em que parte do corpo se encontra a epiglote?", ["Boca", "Rim", "Pâncreas", "Estômago"], 0),
  Perguntas("De quem é a famosa frase “Penso, logo existo”?", ["Platão", "Galileu Galilei", "Descartes", "Sócrates"], 2),
  Perguntas("De onde é a invenção do chuveiro elétrico?", ["França", "Inglaterra", "Brasil", "Itália"], 2),
  Perguntas("Quais o menor e o maior país do mundo?", ["Vaticano e Rússia", "Nauru e China", "Mônaco e Canadá", "Malta e Estados Unidos"], 0),
  Perguntas("Qual o nome do presidente do Brasil que ficou conhecido como Jango?", ["Jânio Quadros", "João Figueiredo", "João Goulart", "Jacinto Anjos"], 2),
  Perguntas("Qual o livro mais vendido no mundo a seguir à Bíblia?", ["O Senhor dos Anéis", "Ela, a Feiticeira", "O Pequeno Príncipe", "Dom Quixote"], 3),
  Perguntas("Quantas casas decimais tem o número pi?", ["Duas", "Milhares", "Vinte", "Infinitas"], 3),
  Perguntas("Atualmente, quantos elementos químicos a tabela periódica possui?", ["113", "109", "118", "140"], 2),
  Perguntas("Quais os países que têm a maior e a menor expectativa de vida do mundo?", ["Japão e Serra Leoa", "Austrália e Afeganistão", "Itália e Chade", "Brasil e Congo"], 0),
  Perguntas("O que a palavra legend significa em português?", ["Legenda", "Conto", "Lenda", "Legendário"], 2),
  Perguntas("Qual o número mínimo de jogadores em cada time numa partida de futebol?", ["8", "10", "9", "7"], 3),
  Perguntas("Quem pintou 'Guernica'?", ["Paul Cézanne", "Pablo Picasso", "Diego Rivera", "Tarsila do Amaral"], 1),
  Perguntas("Quanto tempo a luz do Sol demora para chegar à Terra?", ["12 minutos", "1 dia", "12 horas", "8 minutos"], 3),
  Perguntas("Qual a nacionalidade de Che Guevara?", ["Cubana", "Peruana", "Panamenha", "Argentina"], 3),
  Perguntas("Qual a altura da rede de vôlei nos jogos masculino e feminino?", ["2,43 m e 2,24 m", "1,8 m e 1,5 m", "2,5 m e 2,0 m", "2,4 para ambos"], 0),
  Perguntas("Qual personagem folclórico costuma ser agradado pelos caçadores com a oferta de fumo?", ["Caipora", "Saci", "Lobisomem", "Boitatá"], 0),
  Perguntas("Em que período da pré-história o fogo foi descoberto?", ["Neolítico", "Paleolítico", "Idade dos Metais", "Idade Média"], 1),
  Perguntas("Qual das alternativas abaixo apenas contêm classes de palavras?", ["Vogais, semivogais e consoantes", "Artigo, verbo transitivo e verbo intransitivo", "Substantivo, verbo e preposição", "Hiatos, ditongos e tritongos"], 3),
  Perguntas("Qual a montanha mais alta do Brasil?", ["Pico da Neblina", "Pico Paraná", "Monte Roraima", "Pico Maior de Friburgo"], 0),
  Perguntas("Qual a velocidade da luz?", ["300 000 000 metros por segundo (m/s)", "150 000 000 metros por segundo (m/s)", "199 792 458 metros por segundo (m/s)", "299 792 458 metros por segundo (m/s)"], 3),
  Perguntas("Em qual local da Ásia o português é língua oficial?", ["Índia", "Filipinas", "Moçambique", "Macau"], 3),
  Perguntas("'It is six twenty' ou 'twenty past six'. Que horas são em inglês?", ["12:06", "6:20", "2:20", "6:02"], 1),
  Perguntas("Quem é o autor de “O Príncipe”?", ["Maquiavel", "Antoine de Saint-Exupéry", "Montesquieu", "Rousseau"], 0),
  Perguntas("Como é a conjugação do verbo caber na 1.ª pessoa do singular do presente do indicativo?", ["Eu caibo", "Ele cabe", "Que eu caiba", "Eu cabo"], 3),
  Perguntas("Quais destas doenças são sexualmente transmissíveis?", ["Aids, tricomoníase e ebola", "Chikungunya, aids e herpes genital", "Gonorreia, clamídia e sífilis", "Botulismo, cistite e gonorreia"], 2),
  Perguntas("Qual destes países é transcontinental?", ["Filipinas", "Marrocos", "Rússia", "Groenlândia"], 2),
  Perguntas("Em qual das orações abaixo a palavra foi empregada incorretamente?", ["É um mau vendedor.", "Esse é o mal de todos.", "É um homem mal.", "Mais uma vez, portou-se mal."], 2),
  Perguntas("Qual foi o recurso utilizado inicialmente pelo homem para explicar a origem das coisas?", ["A Filosofia", "A Biologia", "A Mitologia", "A Astronomia"], 2),
  Perguntas("", ["", "", "", ""], 99),
  Perguntas("", ["", "", "", ""], 99),
  Perguntas("", ["", "", "", ""], 99),
  Perguntas("", ["", "", "", ""], 99),
  Perguntas("", ["", "", "", ""], 99),








];

Config configGlobal = Config();
